In [1]:
import pandas
import numpy

In [2]:
db=pandas.read_csv('simple.csv')

In [25]:
db

hrs  marks  no
0    1     20  23
1    2     30  22
2    4     50  20
3    5     60  19
4    6     70  18

In [28]:
x=db[["hrs","no"]]

In [29]:
type(db)

pandas.core.frame.DataFrame

In [30]:
y=db["marks"]

In [7]:
type(x)

pandas.core.series.Series

In [31]:
x=x.values

In [32]:
type(x)

numpy.ndarray

In [34]:
x=x.reshape(5,2)

In [35]:
from sklearn.linear_model import LinearRegression

In [36]:
mind=LinearRegression()

In [37]:
mind.fit(x,y)

LinearRegression()

In [42]:
mind.predict([[9,14]])

array([98.4478897])

In [43]:
mind.coef_

array([11.5521103,  1.5521103])

In [16]:
mind.intercept_

10.0

In [17]:
import joblib

In [18]:
joblib.dump(mind,'marks.pk1')

['marks.pk1']

In [19]:
joblib.load('marks.pk1')

LinearRegression()

In [20]:
mind.predict([[8]])

array([90.])

In [21]:
import joblib

In [22]:
mind.predict([[8]])

array([90.])

In [23]:
2

2